# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hierachain.integration.proto import hierachain_pb2 as api_dot_proto_dot_hierachain__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/proto/hierachain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HieraChainEngineStub(object):
    """HieraChainEngine is the main service for transaction processing.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitBatch = channel.unary_unary(
                '/hierachain.HieraChainEngine/SubmitBatch',
                request_serializer=api_dot_proto_dot_hierachain__pb2.TransactionBatch.SerializeToString,
                response_deserializer=api_dot_proto_dot_hierachain__pb2.BatchResult.FromString,
                _registered_method=True)
        self.StreamTransactions = channel.stream_stream(
                '/hierachain.HieraChainEngine/StreamTransactions',
                request_serializer=api_dot_proto_dot_hierachain__pb2.Transaction.SerializeToString,
                response_deserializer=api_dot_proto_dot_hierachain__pb2.TxStatus.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/hierachain.HieraChainEngine/HealthCheck',
                request_serializer=api_dot_proto_dot_hierachain__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_proto_dot_hierachain__pb2.HealthResponse.FromString,
                _registered_method=True)


class HieraChainEngineServicer(object):
    """HieraChainEngine is the main service for transaction processing.
    """

    def SubmitBatch(self, request, context):
        """SubmitBatch submits a batch of transactions for processing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTransactions(self, request_iterator, context):
        """StreamTransactions streams transactions for high-throughput processing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck returns the health status of the engine.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HieraChainEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitBatch,
                    request_deserializer=api_dot_proto_dot_hierachain__pb2.TransactionBatch.FromString,
                    response_serializer=api_dot_proto_dot_hierachain__pb2.BatchResult.SerializeToString,
            ),
            'StreamTransactions': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTransactions,
                    request_deserializer=api_dot_proto_dot_hierachain__pb2.Transaction.FromString,
                    response_serializer=api_dot_proto_dot_hierachain__pb2.TxStatus.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=api_dot_proto_dot_hierachain__pb2.Empty.FromString,
                    response_serializer=api_dot_proto_dot_hierachain__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hierachain.HieraChainEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hierachain.HieraChainEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HieraChainEngine(object):
    """HieraChainEngine is the main service for transaction processing.
    """

    @staticmethod
    def SubmitBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hierachain.HieraChainEngine/SubmitBatch',
            api_dot_proto_dot_hierachain__pb2.TransactionBatch.SerializeToString,
            api_dot_proto_dot_hierachain__pb2.BatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTransactions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hierachain.HieraChainEngine/StreamTransactions',
            api_dot_proto_dot_hierachain__pb2.Transaction.SerializeToString,
            api_dot_proto_dot_hierachain__pb2.TxStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hierachain.HieraChainEngine/HealthCheck',
            api_dot_proto_dot_hierachain__pb2.Empty.SerializeToString,
            api_dot_proto_dot_hierachain__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
