apiVersion: ledger
kind: Service
metadata:
  name: ipfs-headless
  namespace: hierachain
  labels:
    app: ipfs
spec:
  ports:
    - port: 4001 # Swarm port
      name: swarm
    - port: 5001 # API port
      name: api
    - port: 8080 # Gateway port
      name: gateway
  clusterIP: None # This makes it a headless service
  selector:
    app: ipfs